### PR TITLE
Update conda-setup.sh

### PR DESCRIPTION
**Pull request by Bachmann1234**
This script was failing for me. took me a second to realize what was happening. The first command failed but the script kept going. This command will have the script print out each step and blow up if it fails.

### CODE REVIEW

**Comment by ericmjl** [comment]
Thanks for the patch, @Bachmann1234! See you tomorrow!

**Comment by ericmjl** [comment]
Btw, what's the issue with the conda env command? Hoping to fix that before tomorrow.

**Comment by Bachmann1234** [comment]
@ericmjl oh it was my bad. I did not have conda installed and in my path. Once I had the script fail fast it was super clear. 

Looking at the docs I apparently skimmed "If you have the Anaconda distribution" and went straight to "bash conda-setup.sh" :-P

**Comment by ericmjl** [comment]
@Bachmann1234 haha, no worries! 😄

**Pull request merged**
