### PR TITLE
Airport case study notebook

### PR DESCRIPTION
**Pull request by MridulS**
@ericmjl can you merge this and trigger a build at Leanpub, I want to make sure everything looks pretty out there. :)

### CODE REVIEW

**Comment by ericmjl** [comment]
@MridulS I can, but in the build step, the notebooks have to execute programmatically from top-to-bottom first in order for the LFM markdown files to be generated before the TOC (Book.txt) is generated that LeanPub uses to generate the final PDF. Can you make sure the code executes correctly first?

**Comment by ericmjl** [comment]
I'll be only working on a branch this weekend, so once the notebook executes without error, I'll merge, and then you can directly push changes to master.

**Comment by MridulS** [comment]
ahh, is it possible to have a cell in the notebook which fails intentionally? Travis is error-ing out at a cell which I want to fail.

**Comment by ericmjl** [comment]
I see! For now, sneak it into a Markdown block and format it as Python. I think I did that in one of the earlier notebooks.

**Comment by ericmjl** [comment]
I did some sleuthing around:

[This issue](https://github.com/ipython/ipython/issues/1977#issuecomment-436190949) tells me that we can tag a cell with `raises-exception`. Tagging has been problematic for me, though, so I'm not sure whether this will work for us.

**Comment by MridulS** [comment]
I’ll just use markdown for the time being :)

On 11-Jul-2020, at 20:30, Eric Ma <notifications@github.com<mailto:notifications@github.com>> wrote:



I did some sleuthing around:

This issue<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fipython%2Fipython%2Fissues%2F1977%23issuecomment-436190949&data=02%7C01%7C%7C0071f69f36814f1db92c08d825ab2835%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637300764322337182&sdata=ZCN865f0PjyfC%2FvXOjyiQH64IrKiQbIvDFKb6Al3FEs%3D&reserved=0> tells me that we can tag a cell with raises-exception. Tagging has been problematic for me, though, so I'm not sure whether this will work for us.

**Comment by ericmjl** [comment]
Merged!

**Comment by ericmjl** [comment]
Also I just triggered a new build.

You know, I'm really tempted at this point to just pony up the extra $4 and pay for the API access. Then I won't have to keep triggering a new build lol.

**Comment by MridulS** [comment]
I checked the new build, but it doesn't have the changes :/

**Comment by MridulS** [comment]
Stupid question, if I want to regenerate a build on the web interface at leanpub. I go to preview new version and then click on create preview?

**Comment by ericmjl** [comment]
Yes, that is right. Super weird, I have to check the script/markua.ipynb notebook.

**Comment by MridulS** [comment]
The .csv PR seem to have fixed it. All looks good on Leanpub now. :)

On 11-Jul-2020, at 22:42, Eric Ma <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes, that is right. Super weird, I have to check the script/markua.ipynb notebook.

**Pull request merged**
