### PR TITLE
Update changes to multigraph keys in nx2.5

### PR DESCRIPTION
**Pull request by MridulS**
some upgrades to nx2.5 which makes the code a bit more cleaner.

### CODE REVIEW

**Comment by ericmjl** [comment]
Looks like everything is passing, @MridulS - wanna merge?

**Comment by MridulS** [comment]
@ericmjl sure! I'll probably go looking for more nx2.5 changes in the notebooks. We could a nx2.5 release after that :)

**Comment by MridulS** [comment]
@ericmjl Does it make sense to do a GitHub release too for NAMS? There were a couple of releases for conferences https://github.com/ericmjl/Network-Analysis-Made-Simple/releases . Going forward we can have releases pinned to maybe networkx releases? (The current HEAD in master could be tagged to nx2.4 and released on GitHub)

**Comment by ericmjl** [comment]
Sounds like a great idea! I'll go ahead and cut a new release right now then. Feel free to do the honors once you're done with nx2.5!

**Comment by ericmjl** [comment]
@MridulS just a gentle nudge here to see if we should get this merged or not -- please let me know! Can also opt to break this down into more bite-sized chunks.

**Comment by MridulS** [comment]
Yeah, please go ahead and merge this. I can send in a new PR if I find code blocks which can be updated :)

**Pull request merged**
